# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2e4b6e439ffe92b98683a0abfe0b1f6a52c1c0b92a87d743611e455b520f681d4d32d02fe5276d19967eaac3e512aa788a359f1a57168afcc49d12c57aea538

test:
  secret_key_base: 8ce227aec3169d66b9297ed997a8db8b35901f1f640ab69e230825f7172b90e93da9172a86e8f64f2a8a4b12a02945f14213721a3f223410a8bcc659d64c68d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
